version: '3.9'
services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - backend
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    env_file:
      - ../backend/.env.example
    ports:
      - '4000:4000'
